name: Deploy Blog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Content (This Repo)
        uses: actions/checkout@v4
        with:
          path: content

      - name: Checkout Mizuki Theme
        uses: actions/checkout@v4
        with:
          repository: LyraVoid/Mizuki
          path: mizuki

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: mizuki/pnpm-lock.yaml

      - name: Install Dependencies
        working-directory: mizuki
        run: |
          ls
          pnpm install

      - name: Sync and Overwrite Content
        run: |
          rm -rf mizuki/src/content/* || true
          rsync -av content/ mizuki/ --exclude=.git

      - name: Build
        working-directory: mizuki
        run: pnpm build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./mizuki/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
